### ISSUE TITLE
[Bug]: Cannot open app package: Error in parsing the app package

### ISSUE THREAD

**Issue by JasonWei512** [microsoft/win32-app-isolation#15]
### Version

Windows 11 22623.1245
Win32 app isolation v0.1.0

### Repro Steps

I tried to create an isolated package for the code editor [Lapce v0.2.7](https://github.com/lapce/lapce/releases/tag/v0.2.7).
I downloaded [Lapce-windows.msi](https://github.com/lapce/lapce/releases/download/v0.2.7/Lapce-windows.msi), and followed the [guide](https://github.com/microsoft/win32-app-isolation/blob/edea30e14e09691bd9a05fd4a20a45464ff2a5b1/docs/packaging/msix-packaging-tool.md) to create a package.
I used a self signed PFX certificate to sign the package.

App manifest:

<details>
    <summary>The default app manifest</summary>

    <?xml version="1.0" encoding="utf-8"?>
    <Package xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10" xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10" xmlns:uap10="http://schemas.microsoft.com/appx/manifest/uap/windows10/10" xmlns:desktop7="http://schemas.microsoft.com/appx/manifest/desktop/windows10/7" xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities" IgnorableNamespaces="uap uap10 desktop7 rescap">
    
    <Identity Name="Lapce" Publisher="CN=MY_PUBLISHER_NAME" Version="0.2.7.0" ProcessorArchitecture="x64" />
    <Properties>
        <DisplayName>Lapce</DisplayName>
        <PublisherDisplayName>Lapce</PublisherDisplayName>
        <Description>Lapce</Description>
        <Logo>Assets\StoreLogo.png</Logo>
        <uap10:PackageIntegrity>
        <uap10:Content Enforcement="on" />
        </uap10:PackageIntegrity>
    </Properties>
    <Resources>
        <Resource Language="en-us" />
    </Resources>
    <Dependencies>
        <TargetDeviceFamily Name="Windows.Desktop" MinVersion="10.0.17763.0" MaxVersionTested="10.0.25865.1000" />
    </Dependencies>
    <Applications>
        <Application Id="LAPCE" Executable="VFS\ProgramFilesX64\Lapce\lapce.exe" EntryPoint="Windows.FullTrustApplication">
        <uap:VisualElements BackgroundColor="transparent" DisplayName="Lapce" Square150x150Logo="Assets\LAPCE-Square150x150Logo.png" Square44x44Logo="Assets\LAPCE-Square44x44Logo.png" Description="Lapce">
            <uap:DefaultTile Wide310x150Logo="Assets\LAPCE-Wide310x150Logo.png" Square310x310Logo="Assets\LAPCE-Square310x310Logo.png" Square71x71Logo="Assets\LAPCE-Square71x71Logo.png" />
        </uap:VisualElements>
        <Extensions>
            <desktop7:Extension Category="windows.shortcut">
            <desktop7:Shortcut File="[{Common Programs}]\Lapce\Lapce.lnk" Icon="[{Package}]\VFS\ProgramFilesX64\Lapce\lapce.exe" Description="Lightning-fast and Powerful Code Editor" />
            </desktop7:Extension>
        </Extensions>
        </Application>
    </Applications>
    <Capabilities>
        <rescap:Capability Name="runFullTrust" />
    </Capabilities>
    </Package>
</details>

<details>
    <summary>The app manifest I used</summary>

    <?xml version="1.0" encoding="utf-8"?>
    <Package xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10" xmlns:previewsecurity2="http://schemas.microsoft.com/appx/manifest/preview/windows10/security/2" xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10" xmlns:uap10="http://schemas.microsoft.com/appx/manifest/uap/windows10/10" xmlns:desktop7="http://schemas.microsoft.com/appx/manifest/desktop/windows10/7" xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities" IgnorableNamespaces="uap uap10 desktop7 rescap previewsecurity2">
    
    <Identity Name="Lapce" Publisher="CN=MY_PUBLISHER_NAME" Version="0.2.7.0" ProcessorArchitecture="x64" />
    <Properties>
        <DisplayName>Lapce</DisplayName>
        <PublisherDisplayName>Lapce</PublisherDisplayName>
        <Description>Lapce</Description>
        <Logo>Assets\StoreLogo.png</Logo>
        <uap10:PackageIntegrity>
        <uap10:Content Enforcement="on" />
        </uap10:PackageIntegrity>
    </Properties>
    <Resources>
        <Resource Language="en-us" />
    </Resources>
    <Dependencies>
        <TargetDeviceFamily Name="Windows.Desktop" MinVersion="10.0.22622.0" MaxVersionTested="10.0.22622.0" />
    </Dependencies>
    <Applications>
        <Application Id="LAPCE" Executable="VFS\ProgramFilesX64\Lapce\lapce.exe" uap10:TrustLevel="appContainer" previewsecurity2:RuntimeBehavior="appSilo">
        <uap:VisualElements BackgroundColor="transparent" DisplayName="Lapce" Square150x150Logo="Assets\LAPCE-Square150x150Logo.png" Square44x44Logo="Assets\LAPCE-Square44x44Logo.png" Description="Lapce">
            <uap:DefaultTile Wide310x150Logo="Assets\LAPCE-Wide310x150Logo.png" Square310x310Logo="Assets\LAPCE-Square310x310Logo.png" Square71x71Logo="Assets\LAPCE-Square71x71Logo.png" />
        </uap:VisualElements>
        <Extensions>
            <desktop7:Extension Category="windows.shortcut">
            <desktop7:Shortcut File="[{Common Programs}]\Lapce\Lapce.lnk" Icon="[{Package}]\VFS\ProgramFilesX64\Lapce\lapce.exe" Description="Lightning-fast and Powerful Code Editor" />
            </desktop7:Extension>
        </Extensions>
        </Application>
    </Applications>
    <Capabilities>
        <rescap:Capability Name="runFullTrust" />
    </Capabilities>
    </Package>
</details>

And I succeed to generate an MSIX package. But...

### Unexpected Results

When I double clicked the generated MSIX package, I got an error: `Cannot open app package: Error in parsing the app package`.

![Screenshot](https://github.com/microsoft/win32-app-isolation/assets/16899918/1229eaad-237c-4324-898a-9c58a870b3dd)

If I don't replace `entrypoint` with `uap10:TrustLevel="appContainer" previewsecurity2:RuntimeBehavior="appSilo"` in app manifest when packaging as the [guide](https://github.com/microsoft/win32-app-isolation/blob/edea30e14e09691bd9a05fd4a20a45464ff2a5b1/docs/packaging/msix-packaging-tool.md) does, I can install the package, but it's no longer isolated.

**Comment by lilybarkley-msft** [comment]
Hey JasonWei512,

The min build provided in the documentation is incorrect. I'm currently working on finding a more exact min build and will update the documentation once I do. I was able to successfully package and install on 25375, though I suspect the actual min build is a little lower than that.

Thanks,
Lily

**Comment by lilybarkley-msft** [comment]
I've opened a PR to update the documentations, `10.0.25229.0` is the actual min build you should be targeting.

**Comment by lilybarkley-msft** [comment]
Closing the issue as https://github.com/microsoft/win32-app-isolation/pull/18 has been checked in
