### ISSUE TITLE
[Inquiry]: How does this affect the UI?

### ISSUE THREAD

**Issue by mikehearn** [microsoft/win32-app-isolation#17]
### Description

If win32 sandboxing is enabled, is that visible to end users anywhere (e.g. appinstaller)? If not, is it meant to be a feature for improving the security of the app itself? This is how Apple advertises its own app sandbox for example: it's not to let you install apps of uncertain provenance or trustworthiness, but rather, to reduce the impact of security bugs in the app itself. But I think what most people want is the ability to install apps without worrying about whether they're trustable or not.

**Comment by cchavez-msft** [comment]
Hi, @mikehearn. Thank you so much for your input. Please, if you think you have more inquiries related to this issue, feel free to re-open it. We highly appreciate your participation.

Thank you again.
