### ISSUE TITLE
[Docs]: `runFullTrust` is not necessary for AppSilo

### ISSUE THREAD

**Issue by AndromedaMelody** [microsoft/win32-app-isolation#20]
### Links

https://github.com/microsoft/win32-app-isolation/blob/1f55dcd6c9708754c983f9318f7878ddb2d4b401/docs/packaging/msix-packaging-tool.md?plain=1#L58
https://github.com/microsoft/win32-app-isolation/blob/1f55dcd6c9708754c983f9318f7878ddb2d4b401/docs/packaging/msix-packaging-tool.md?plain=1#L75

### Description

I try to use AppSilo without runFullTrust, and the package install successfully.

I think if we needn't any feature of Medium Integration Level, we shouldn't add restricted capability runFullTrust. As a result, the document of [MSIX -> Isolated Win32](https://github.com/microsoft/win32-app-isolation/blob/1f55dcd6c9708754c983f9318f7878ddb2d4b401/docs/packaging/msix-packaging-tool.md#msix---isolated-win32) can add a step: 

> Delete `<rescap:Capability Name="runFullTrust" />` in `<Capabilities>`

![Screenshot 2023-05-26 000123](https://github.com/microsoft/win32-app-isolation/assets/57533055/973d3218-903c-4a55-9f77-94a8e9cee693)

**Comment by ddsilva-msft** [comment]
@AndromedaMelody thank you for reporting this. runFullTrust is definitely not required and should be avoided for isolated Win32 applications. We'll get the image fixed.
