### ISSUE TITLE
[Bug]: `PartialTrustApplication` and `isolatedWin32-* Capabilities` can't be declared in one package

### ISSUE THREAD

**Issue by AndromedaMelody** [microsoft/win32-app-isolation#23]
### Version

Windows: 10.0.25370.1

### Repro Steps

According to [AppxManifest Document](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-application#combinations-of-activation-info-attributes) and microsoft/WindowsAppSDK#219 :

1. Add `EntryPoint="windows.partialTrustApplication"` or `uap10:RuntimeBehavior="packagedClassicApp" uap10:TrustLevel="appContainer"` in `<Application>`;
   Add `uap10:TrustLevel="appContainer" previewsecurity2:RuntimeBehavior="appSilo"` in `<Application>`.
2. Add `isolatedWin32-*` in `<Capabilities>`.
3. Register the package and run.

### Unexpected Results

The application(PartialTrust) can't start, and the application(AppSilo) start properly.

Are there any relation between PartialTrust and AppSilo?

![Screenshot 2023-05-26 004704](https://github.com/microsoft/win32-app-isolation/assets/57533055/baccbdd0-3101-4d64-a4a9-7e5a44bd14f2)

**Comment by lilybarkley-msft** [comment]
I will update the documentation to reflect this, but isolated win32 apps aren't compatible with other application types within the same package

**Comment by MouriNaruto** [comment]
@lilybarkley-msft 

> but isolated win32 apps aren't compatible with other application types within the same package

In my opinion, some components in a package may not need the extra attacking surface provided by the App Silo. So, it's necessary for support both App Silo and Partial Trust in one app package. 

Even I hope we can run something as the pure App Container (even the Low Privileged App Container which used in Chromium-based web browsers) or Partial Trust in an app which run as App Silo for continually improving the security and privacy.

Kenji Mouri

**Comment by lilybarkley-msft** [comment]
> In my opinion, some components in a package may not need the extra attacking surface provided by the App Silo. So, it's necessary for support both App Silo and Partial Trust in one app package. 

This is a good point, I'll have a discussion about this with the rest of the team
