### ISSUE TITLE
[Docs]: Clarify runtime and development targets for Win32 App Isolation

### ISSUE THREAD

**Issue by riverar** [microsoft/win32-app-isolation#29]
### Description

It should be made clear which versions and SKUs of Windows support Win32 App Isolation (e.g., retail 22621, beta X, dev Y, canary Z) and which capabilities are supported where. Also consider which targets are needed for _development_ (the tooling in this repository) if it doesn't match the first list.

**Comment by ddsilva-msft** [comment]
Hey @riverar we have the versions covered in the windows-release-notes.md file, but we'll clarify the supported SKUs too. We'll look into the supported OS versions for the tools as well.

**Comment by riverar** [comment]
Is that checked into this repository somewhere?

**Comment by riverar** [comment]
I saw https://github.com/microsoft/win32-app-isolation/blob/main/relnotes/windows-release-notes.md but it doesn't seem accurate or complete. Win32 App Isolation [is documented as shipping in 22621](https://blogs.windows.com/windowsexperience/2023/05/23/announcing-new-windows-11-innovation-with-features-for-secure-efficient-it-management-and-intuitive-user-experience/) right? But the documentation only indicates it's available via Canary builds of Windows.

**Comment by ddsilva-msft** [comment]
The Public Preview called out in the blog is only available through Windows Insiders via the Canary channel. The release notes are accurate about the supported builds.

**Comment by riverar** [comment]
Got it, thanks!

**Comment by tiangao-ms** [comment]
Close as clarified.
