### ISSUE TITLE
Unable to parse manifest after removing `EntryPoint`

### ISSUE THREAD

**Issue by knightzf** [microsoft/win32-app-isolation#55]
### Version

Windows version: Windows 10 22H2 (OS Build 19045.3086)
Win32-app-isolation version: v0.1.1 

### Repro Steps

I tried to follow the document in https://github.com/microsoft/win32-app-isolation/blob/main/docs/packaging/msix-packaging-tool.md and got `Unable to parse manifest` error when setting the trustlevel.

**Before:**
![Capture](https://github.com/microsoft/win32-app-isolation/assets/4433475/d5996e23-9766-43de-8e62-3a4b65f2a7e8)

**After:**
![Capture2](https://github.com/microsoft/win32-app-isolation/assets/4433475/f31ad3be-7506-4aa9-ad20-0e6c814b4bcd)

### Unexpected Results

![image](https://github.com/microsoft/win32-app-isolation/assets/4433475/f3a597d2-4075-4c92-8778-deefd4a75f2d)

**Comment by cchavez-msft** [comment]
Hi, @knightzf. Thank you so much for engaging with us. We appreciate your insights. What we can see is that the OS build is not the right one. It should be at least 25357 as you can see in the link at the end of the Getting Started section of the main page: https://github.com/microsoft/win32-app-isolation/blob/main/relnotes/windows-release-notes.md
Please, let us know if this helps.

**Comment by knightzf** [comment]
@cchavez-msft Thanks for the info! So it'll only work on window 11?

**Comment by tiangao-ms** [comment]
> @cchavez-msft Thanks for the info! So it'll only work on window 11?

The isolated app for now would only work on win 11 with version number > 25357 (I believe it's Windows Insider only now). However, the reason of your specific failure was probably that you forgot to include uap10 header (we've realized that there's a missing piece in our docs and we will fix it soon).

**Comment by windcloudftw** [comment]
same problem in WIP 1000.26241.5000.0

**Comment by tiangao-ms** [comment]
@windcloudftw are you using the MSIX Packaging Tool we provided in our github?

**Comment by windcloudftw** [comment]
> @windcloudftw are you using the MSIX Packaging Tool we provided in our github?

yes.The MSIX Packaging Tool reminds me that 'cmd' violates pattern constraint of '\bms-resource:.{1,256}'.This problem did not occur on my wip system last month, and I was able to modify the manifest file and package it normally at that time. This problem seems to have occurred after the recent system upgrade

**Comment by GF-Huang** [comment]
Same issue.

<img width="769" alt="image" src="https://github.com/microsoft/win32-app-isolation/assets/4510984/817c8665-8d8b-4bb6-ad3e-271984316216">

```xml
<?xml version="1.0" encoding="utf-8"?>
<Package xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10" xmlns:previewsecurity2="http://schemas.microsoft.com/appx/manifest/preview/windows10/security/2" xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10" xmlns:uap10="http://schemas.microsoft.com/appx/manifest/uap/windows10/10" xmlns:desktop7="http://schemas.microsoft.com/appx/manifest/desktop/windows10/7" xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities" IgnorableNamespaces="uap uap10 desktop7 rescap previewsecurity2">
  <!--Package created by MSIX Packaging Tool version: 1.2024.405.0-->
  <Identity Name="WeChat" Publisher="CN=Win32 App Isolation, C=CN" Version="3.9.11.0" ProcessorArchitecture="x64" />
  <Properties>
    <DisplayName>微信</DisplayName>
    <PublisherDisplayName>Win32 App Isolation</PublisherDisplayName>
    <Logo>Assets\StoreLogo.png</Logo>
    <uap10:PackageIntegrity>
      <uap10:Content Enforcement="on" />
    </uap10:PackageIntegrity>
  </Properties>
  <Resources>
    <Resource Language="en-us" />
  </Resources>
  <Dependencies>
    <TargetDeviceFamily Name="Windows.Desktop" MinVersion="10.0.22631.0" MaxVersionTested="10.0.22631.0" />
    <PackageDependency Name="Microsoft.WindowsAppRuntime.1.4" MinVersion="4000.1010.1349.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />
  </Dependencies>
  <Applications>
    <Application Id="WECHAT" Executable="VFS\ProgramFilesX64\Tencent\WeChat\WeChat.exe" uap10:TrustLevel="appContainer" previewsecurity2:RuntimeBehavior="appSilo">
      <uap:VisualElements BackgroundColor="transparent" DisplayName="微信" Square150x150Logo="Assets\WECHAT-Square150x150Logo.png" Square44x44Logo="Assets\WECHAT-Square44x44Logo.png" Description="微信">
        <uap:DefaultTile Wide310x150Logo="Assets\WECHAT-Wide310x150Logo.png" Square310x310Logo="Assets\WECHAT-Square310x310Logo.png" Square71x71Logo="Assets\WECHAT-Square71x71Logo.png" />
      </uap:VisualElements>
      <Extensions>
        <desktop7:Extension Category="windows.shortcut">
          <desktop7:Shortcut File="[{Desktop}]\微信.lnk" Icon="[{Package}]\VFS\ProgramFilesX64\Tencent\WeChat\WeChat.exe" />
        </desktop7:Extension>
        <desktop7:Extension Category="windows.shortcut">
          <desktop7:Shortcut File="[{Common Programs}]\微信\微信.lnk" Icon="[{Package}]\VFS\ProgramFilesX64\Tencent\WeChat\WeChat.exe" />
        </desktop7:Extension>
      </Extensions>
    </Application>
  </Applications>
  <Capabilities>
    <Capability Name="internetClient" />
    <rescap:Capability Name="accessoryManager" />
    <rescap:Capability Name="isolatedWin32-print" />
    <rescap:Capability Name="isolatedWin32-sysTrayIcon" />
    <rescap:Capability Name="isolatedWin32-shellExtensionContextMenu" />
    <rescap:Capability Name="isolatedWin32-promptForAccess" />
    <rescap:Capability Name="isolatedWin32-accessToPublisherDirectory" />
    <rescap:Capability Name="isolatedWin32-dotNetBreadcrumbStore" />
    <rescap:Capability Name="isolatedWin32-profilesRootMinimal" />
    <rescap:Capability Name="isolatedWin32-userProfileMinimal" />
    <rescap:Capability Name="isolatedWin32-volumeRootMinimal" />
    <DeviceCapability Name="microphone" />
    <DeviceCapability Name="webcam" />
  </Capabilities>
</Package>
```

![image](https://github.com/microsoft/win32-app-isolation/assets/4510984/2207020b-f178-4e99-843d-b602933c8c6b)

**Comment by tiangao-ms** [comment]
> yes.The MSIX Packaging Tool reminds me that 'cmd' violates pattern constraint of '\bms-resource:.{1,256}'.This problem did not occur on my wip system last month, and I was able to modify the manifest file and package it normally at that time. This problem seems to have occurred after the recent system upgrade

The MSIX Packaging Tool might be updated so please double check the version.

**Comment by tiangao-ms** [comment]
@GF-Huang - for now, you have to use the exact MSIX Packaging tool we provided in our github release. The officially released version does not have the feature yet. (It will, soon).

**Comment by GF-Huang** [comment]
> @GF-Huang - for now, you have to use the exact MSIX Packaging tool we provided in our github release. The officially released version does not have the feature yet. (It will, soon).

But the MS Store version seems later than the Github release version, why it has not the older feature?

**Comment by tiangao-ms** [comment]
> But the MS Store version seems later than the Github release version, why it has not the older feature?

Because the version we provided is an internal version, it's customized for Win32 app isolation. The official release requires a longer process, so the feature is not in the latest version yet.
