### ISSUE TITLE
[Inquiry]: Does this project provide UI isolation for Win32 apps?

### ISSUE THREAD

**Issue by HackTestes** [microsoft/win32-app-isolation#60]
### Description

I would like to know if the isolation provided by this project also covers UI elements. For example, can this project isolate keyboard input and screen capture? Can only capture keyboard input in focus?

I searched throughout all of the documentation (inside and outside of the repo) and I couldn't find any mention about UI permissions explicitly, just general things about the [AppContainer Isolation](https://learn.microsoft.com/en-us/windows/win32/secauthz/appcontainer-isolation). However, I assume this project does a few things differently for Win32 apps, so the previous reference might not apply here. I also didn't find any capabilities that pertain to UI in the [Windows API documentation](https://learn.microsoft.com/en-us/windows/win32/secauthz/capability-sid-constants) for AppContainer capabilities.

I have also tried executing an app inside an MSIX to test such isolation mechanisms, but couldn't manage to make it work (I wasn't able to run anything unfortunately).

This is why I am opening this issue. Thanks in advance.

**Comment by ddsilva-msft** [comment]
@HackTestes the isolation provided by this project is based on the AppContainer primitive so the same input and window isolation properties for AppContainers would apply here.
